[package]
name = "lindera-py"
version = "0.24.0"
edition = "2021"
description = "Python binding for Lindera."
documentation = "https://docs.rs/lindera-py"
homepage = "https://github.com/lindera-morphology/lindera-py"
repository = "https://github.com/lindera-morphology/lindera-py"
readme = "README.md"
keywords = ["morphological", "analysis", "library", "python"]
categories = ["text-processing"]
license = "MIT"

[lib]
name = "lindera_py"
crate-type = ["cdylib"]

[features]
default = []  # No directories included
ipadic = ["lindera-tokenizer/ipadic"]  # Include IPADIC dictionary (Japanese)
unidic = ["lindera-tokenizer/unidic"]  # Include UniDic dictionary (Japanese)
ko-dic = ["lindera-tokenizer/ko-dic"]  # Include ko-dic dictionary (Korean)
cc-cedict = ["lindera-tokenizer/cc-cedict"]  # Include CC-CEDICT dictionary (Chinese)
ipadic-compress = ["lindera-tokenizer/ipadic-compress"]  # Compress IPADIC
unidic-compress = ["lindera-tokenizer/unidic-compress"]  # Compress UniDic
ko-dic-compress = ["lindera-tokenizer/ko-dic-compress"]  # Compress ko-dic
cc-cedict-compress = ["lindera-tokenizer/cc-cedict-compress"]  # Compress CC-CEDICT
ipadic-filter = ["lindera-filter/ipadic"]  # Include filters for IPADIC
unidic-filter = ["lindera-filter/unidic"]  # Include filters for UniDic
ko-dic-filter = ["lindera-filter/ko-dic"]  # Include filters for ko-dic
cc-cedict-filter = ["lindera-filter/cc-cedict"]  # Include filters for CC-CEDICT

[dependencies]
pyo3 = { version = "0.18.2", features = ["extension-module"] }

lindera-analyzer = { version = "0.24.0", path = "../lindera/lindera-analyzer" }
lindera-cc-cedict-builder = { version = "0.24.0", path = "../lindera/lindera-cc-cedict-builder" }
lindera-core = { version = "0.24.0", path = "../lindera/lindera-core" }
lindera-dictionary = { version = "0.24.0", path = "../lindera/lindera-dictionary" }
lindera-filter = { version = "0.24.0", path = "../lindera/lindera-filter" }
lindera-ipadic-builder = { version = "0.24.0", path = "../lindera/lindera-ipadic-builder" }
lindera-ko-dic-builder = { version = "0.24.0", path = "../lindera/lindera-ko-dic-builder" }
lindera-tokenizer = { version = "0.24.0", path = "../lindera/lindera-tokenizer" }
lindera-unidic-builder = { version = "0.24.0", path = "../lindera/lindera-unidic-builder" }
